export const ADVISETOMORROW = [
  {
    id: 12,
    comparisonTempString: "Сегодня немного теплее",
    uvIndexString:
      "это умеренный уровень ультрафиолетового излучения, необходима защита. В полуденные часы с 12 до 14 желательно находиться в тени или в помещении. Вне помещения нужно использовать солнцезащитную одежду, рубашку, солнцезащитные очки, кепку с козырьком, или шляпу с полями. Используйте солнцезащитный крем с ЅРЕ 15+ для открытых участков кожи каждые 1,5 часа или после каждого купания или обильного потоотделения.",
    weatherAdviceString: [],
    clothAdvise: "",
    badWeatherAdvise: "",
    umbrella: "",
    heat: "",
    glasses: "",
    palms: "",
    neck: "",
    jacket: "",
    outerwear: "",
    upCloth: "",
    thermalUnderwear: "",
    downCloth: "",
    boots: "",
    socks: "",
    warmTrousers: "",
    snow: "",
  },
];
