export const TODAY = [
  {
    id: 1,
    day: "Утром",
    tempNumber: 10,
    tempString: "tttt",
    cloudsString: "облочно",
    cloudsImgNumber: 113,
    windNumber: 7,
    windString: "умеренный",
  },
  {
    id: 2,
    day: "Днем",
    tempNumber: 10,
    tempString: "прохладно",
    cloudsString: "облочно",
    cloudsImgNumber: 113,
    windNumber: 7,
    windString: "умеренный",
  },
  {
    id: 3,
    day: "Вечером",
    tempNumber: 10,
    tempString: "прохладно",
    cloudsString: "облочно",
    cloudsImgNumber: 113,
    windNumber: 7,
    windString: "умеренный",
  },
];
